FROM debezium/connect:1.4
COPY ./mongodb-kafka-connect-mongodb-1.4.0.tar.xz /kafka/connect
RUN cd /kafka/connect && tar xvf mongodb-kafka-connect-mongodb-1.4.0.tar.xz && rm mongodb-kafka-connect-mongodb-1.4.0.tar.xz