version: '3.4'

volumes:
  sonic-characters-data:
    name: sonic-characters-data
  sonic-characters-mongo:
    name: sonic-characters-mongo

services:
  postgres:
    container_name: debezium-postgres
    image: postgres:10.6
    environment:
      - "POSTGRES_DB=debezium-demo"
      - "POSTGRES_USER=debeziumuser"
      - "POSTGRES_PASSWORD=debeziumuser"
    ports:
      - 5432:5432
    volumes:
      - "sonic-characters-data:/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes: 
    - "sonic-characters-mongo:/data/db"
    ports:
    - 27017:27017
  
  kafka:
    image: debezium/kafka:1.4
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     
  schema-registry:
    image: confluentinc/cp-schema-registry
    ports:
      - 8181:8181
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=  http://schema-registry:8081
    links:
      - zookeeper
        
  connect:
    image: debezium/connect:1.4
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
     - schema-registry
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
